
-- Rename ST_ID to STUDENT_ID in the STUDENTS table
ALTER TABLE STUDENTS RENAME COLUMN ST_ID TO STUDENT_ID;

-- Change the length of STUDENTS.ST_NAME and STUDENTS.ST_LAST from 20 to 30 
ALTER TABLE STUDENTS
ALTER COLUMN ST_NAME TYPE VARCHAR(30),
ALTER COLUMN ST_LAST TYPE VARCHAR(30);
