-- Rename ST_ID column to STUDENT_ID in the STUDENTS table
ALTER TABLE STUDENTS RENAME COLUMN ST_ID TO STUDENT_ID;

-- Change the length of STUDENTS.ST_NAME and STUDENTS.ST_LAST from 20 to 30 
ALTER TABLE STUDENTS
ALTER COLUMN ST_NAME TYPE VARCHAR(30),
ALTER COLUMN ST_LAST TYPE VARCHAR(30);

-- Create new table for holding the INTERESTS with an array type
CREATE TABLE NEW_INTERESTS (
    STUDENT_ID INT,
    INTERESTS VARCHAR(30)[]
);

-- Populate the NEW_INTERESTS table with grouped(aggregated) interests
INSERT INTO NEW_INTERESTS (STUDENT_ID, INTERESTS)
SELECT STUDENT_ID, ARRAY_AGG(INTEREST)
FROM INTERESTS
GROUP BY STUDENT_ID
ORDER BY STUDENT_ID ASC; 

-- Drop the old INTERESTS table
DROP TABLE INTERESTS;

-- Change the name of NEW_INTERESTS table to INTERESTS
ALTER TABLE NEW_INTERESTS RENAME TO INTERESTS;
